### ISSUE TITLE
Add About me Links to the About Us drop down

### ISSUE THREAD

**Issue by thumula-akhitha** [Rethima-Reddy/mvc-app#7]

**Comment by rohan6471** [comment]
added About me link in the nav bar

**Comment by thumula-akhitha** [comment]
Added about me link in the nav bar

**Comment by Mahender1166** [comment]
Added the link to about me page in the navigation bar

**Comment by Rithima-Reddy** [comment]
Added about me page in the About Us link in the navigation bar.
