### ISSUE TITLE
Add Links to the Nav Bar of different Modules

### ISSUE THREAD

**Issue by thumula-akhitha** [Rethima-Reddy/mvc-app#9]

**Comment by rohan6471** [comment]
added my About me link in nav bar

**Comment by rohan6471** [comment]
added instructors link

**Comment by thumula-akhitha** [comment]
Added Sections module in the Nav Bar

**Comment by Mahender1166** [comment]
Added Students link in the navigation bar

**Comment by Rithima-Reddy** [comment]
Added my module of course in the navigation bar @Rethima-Reddy
